spring.application.name=AirBnb

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnbdb
spring.datasource.username=postgres
spring.datasource.password=410403

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server Configuration
server.servlet.context-path=/api/v1
server.port=8080

# JWT Secret
jwt.secretKey=mysecretkey12345678912345678912345

# Frontend URL
frontend.url=http://localhost:3000

# Stripe Configuration
stripe.secret.key=dummy
stripe.webhook.secret=dummy

# Swagger Configuration
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
